name: Build

on: [push, pull_request]
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run format
        run: npm run format
        working-directory: ./
      - name: Run lint
        run: npm run lint
        working-directory: ./
